services:
  servers:
    build:
      context: ./MQuince
      args:
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: root
        DATABASE_PORT: 5432
        STAGE: test
        PORT: 5000

    image: mquince-postgres
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_PORT: 5432
      STAGE: test
      PORT: 5000

  mysql:
    image: fintrace/postgres-uuid
    container_name: mysql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mquince
    volumes:
      - postgres-data:/var/lib/postgres:rw

volumes:
  postgres-data:
